version: "3.9"
services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    ports:
      - "12323:12323"
    environment:
      - IP=empty
      - PORT=12323
      - JOIN_IP=empty
      - JOIN_PORT=empty
      - STABILIZE_TIME=3000
      - FIX_FINGER_TIME=3000
      - CHECK_PRED_TIME=3000
      - UNIQ_ID=empty
      - SUCC_NO=empty
  peer2:
    depends_on:
      - peer1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    ports:
      - "8080:8080"
    environment:
      - IP=empty
      - PORT=8080
      - JOIN_IP=peer1
      - JOIN_PORT=12323
      - STABILIZE_TIME=100
      - FIX_FINGER_TIME=100
      - CHECK_PRED_TIME=100
      - UNIQ_ID=empty
      - SUCC_NO=empty

