version: "3.9"
services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    network_mode: "host"
    environment:
      - IP=empty
      - PORT=12323
      - JOIN_IP=empty
      - JOIN_PORT=empty
      - STABILIZE_TIME=3000
      - FIX_FINGER_TIME=3000
      - CHECK_PRED_TIME=3000
      - UNIQ_ID=empty
      - SUCC_NO=empty
  peer2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    network_mode: "host"
    environment:
      - IP=empty
      - PORT=12324
      - JOIN_IP=134.122.76.107
      - JOIN_PORT=12323
      - STABILIZE_TIME=3000
      - FIX_FINGER_TIME=3000
      - CHECK_PRED_TIME=3000
      - UNIQ_ID=empty
      - SUCC_NO=empty
  peer3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    network_mode: "host"
    environment:
      - IP=empty
      - PORT=12325
      - JOIN_IP=134.122.74.90
      - JOIN_PORT=12324
      - STABILIZE_TIME=3000
      - FIX_FINGER_TIME=3000
      - CHECK_PRED_TIME=3000
      - UNIQ_ID=empty
      - SUCC_NO=empty

